In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [2]:
#numpy is used to work with the array. the array object in numpy s called
#ndarry: we can create Numpy ndarray object by using the array() function
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
# dimensions in array

In [3]:
#0-D ARRAYS each element in a array is o-d array
import numpy as np
arr-np.array(42)
print(arr)

[1 2 3 4 5 6 7]


In [4]:
#1-D arrays , an array that has 0=d arrays as its elemnts
# is called the unidimensional
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [5]:
#2-D, an array that has 1 d array as its elemnts is called the 2-d array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
#they are often used to represent the matrix

[[1 2 3]
 [4 5 6]]


In [6]:
#3=D, an array that used 2-d array as its elemnts is called the 3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[8,9,10]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 8  9 10]]]


In [9]:
#numpy array provide the ndim attribute that returns an integers that tells the how many dimensions does the array have
import numpy as np
a=np.array(43)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3,4],[4,5,6,7]])
d=np.array([[[1,2,3],[4,5,6]],[[3,5,6],[7,9,0]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)




0
1
2
3


In [13]:
# an array can have any number of dimensions by using the ndim argument
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
# accessing the array elemnts of 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[0])# for accessing the first element of the array
print(arr[1])# for accessing the second elemnt of the array



1
2


In [17]:
# accessing the 2-D array elemnts
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])
print('2nd element on 1st row: ', arr[0, 1])

5th element on 2nd row:  10
2nd element on 1st row:  2


In [18]:
#accessing the 3-D array elemnts
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])#access the thied element of second array if the first array

6


In [24]:
# numpy array slicing
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])#the results includes the start index but excludes the end index
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])#negative slicing
print(arr[1:5:2])#step indexing
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [27]:
#slicing of the 2-d array
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 1:4])#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 2])# from both elements return the index 2

[7 8 9]
[[2 3 4]
 [7 8 9]]
[3 8]


In [29]:
#checking the datatype of tye array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array(['apple','banana','papaya','grapes'])
print(a.dtype)
print(b.dtype)

int32
<U6


In [33]:
#creating the array with the defoned datatype
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
brr = np.array([1, 2, 3, 4], dtype='i')
print(brr)
print(arr)
print(arr.dtype)
print(brr.dtype)

[1 2 3 4]
[b'1' b'2' b'3' b'4']
|S1
int32


In [36]:
#change the dataype from integer to boolean
import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
oldarr=arr.astype(int)
print(oldarr)
print(newarr)
print(newarr.dtype)


[1 0 3]
[ True False  True]
bool


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)
#the copy shouldn't affected by making changes in the original array


[42  2  3  4  5]
[1 2 3 4 5]


In [38]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)
#view affected by making the changes in the original array

[42  2  3  4  5]
[42  2  3  4  5]


In [39]:
#what happened if we make changes in the view
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=42
print(arr)
print(x)
#original arry affected by making the changes in the view

[42  2  3  4  5]
[42  2  3  4  5]


In [40]:
#how to check whether the array ows the data or not
#numpy array has the attribute base that returns none if the array owns the data
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)
#this hows that copy owns the data and view doesn't ows the data


None
[1 2 3 4 5]


In [1]:
#printing the shapen  of 2-D earray
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [2]:
#reshape from 1D to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#reshape from 1D to 3D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
#flattening the array: converting the multidimensional array into 1D array
#we can use reshape(-1) to do this
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)
#we cannot pass -1 in more than on dimension

[1 2 3 4 5 6]


In [8]:
#iterating array
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [9]:
#iterating 2-d arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [10]:
#iterate on each scalar elemnyt of 2-d
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in arr:
        print(y)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [1]:
#iterating the 3D arrays : we need to itersate the elements one by one
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [2]:
#iterate down to the scalars
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [4]:
#iterating arrays using nditer()
#the function nditer() is a helping function that can be used from very basic to vary advanced iteractions.
import numpy as np
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [3]:
#joining the numpy arrays
# we pass a sequence of arrays that we want to join to the concatenate()
#along with the axis.
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
