In [10]:
import numpy as np
myarr=np.array([[3,6,32,7]],np.int8)
myarr[0,1]
myarr.shape
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [1]:
import numpy as np
myarr=np.array([[3,6,32,7]],np.int8)
myarr.shape #tells the size of the arry
myarr[0,1]=45 # we can udate elements in numpy by giving the index
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

In [16]:
#array creation: conversion from other data structures
import numpy as np
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])#using the list
listarray


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [18]:
 import numpy as np
 zeros=np.zeros((2,5))
 zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
import numpy as np
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
import numpy as np
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.89144519e-307, 4.45042358e-308, 1.89145198e-307],
       [6.23046484e-307, 2.22526399e-307, 6.23053614e-307,
        1.29060871e-306, 6.23055651e-307, 1.06811422e-306],
       [3.56043054e-307, 1.37961641e-306, 6.23040033e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [2.22518251e-306, 1.33511969e-306, 6.23058028e-307,
        1.11261774e-306, 8.34420522e-308, 6.23052935e-307]])

In [ ]:
import numpy as np
ide=np.identity(45)
ide
